/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [{
      name: 'Иван',
      email: 'ivan@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Петр',
      email: 'petr@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Врач. В свободное от работы время занимаюсь пулевой стрельбой',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Женя',
      email: 'evgeniy@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Люблю вкусно поесть и кошечек',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Андрей',
      email: 'andrey@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Люблю свою жену',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Олеся',
      email: 'olesya@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Программистка. Люблю свою работу',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Жанна',
      email: 'zhanna@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Мама троих детей',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Юлия',
      email: 'juliya@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Я фронтенд разработчик',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Максим',
      email: 'max@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Тарас',
      email: 'taras@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Игорь',
      email: 'igor@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Елена',
      email: 'helen@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Ренат',
      email: 'renat@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Рома',
      email: 'roma@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Николай',
      email: 'nikolay@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Ярослав',
      email: 'yaroslav@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Саркис',
      email: 'sarkis@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Вика',
      email: 'vika@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
