/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [{
      name: 'Андрей',
      email: 'Andrey@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: 'Andrey.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Вика',
      email: 'Vika@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Врач. В свободное от работы время занимаюсь пулевой стрельбой',
      avatar: 'Viktoria.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Максим',
      email: 'max@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: 'adult-man-face.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Саркис',
      email: 'Sarkis@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Люблю вкусно поесть и кошечек',
      avatar: 'Sarkis.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Андрейка',
      email: 'Andreyka@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Люблю свою жену',
      avatar: '9c5cf74edb5f94f3ad612706f4c6b140.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Олеся',
      email: 'olesya@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Программистка. Люблю свою работу',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Жанна',
      email: 'zhanna@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Мама троих детей',
      avatar: 'DrawingOFaGirl.jpeg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Юлия',
      email: 'juliya@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Я фронтенд разработчик',
      avatar: 'DrawingOFaGirl.jpeg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Тарас',
      email: 'taras@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: 'ManInASuit.jpeg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Игорь',
      email: 'igor@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: 'KurtCobainClock_2550x.webp',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Елена',
      email: 'helen@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: 'WomanBrownEyes.jpeg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Ренат',
      email: 'renat@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: 'Jecson.jpeg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Рома',
      email: 'roma@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Фронтенд разработчик',
      avatar: 'Bruce_Lee.jpeg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Николай',
      email: 'nikolay@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Ярослав',
      email: 'yaroslav@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Саркиска',
      email: 'kiss@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Викус',
      email: 'vika@mail.ru',
      password: '$2b$10$hGZwt5FyjNTuf1J5CjJe/OqKUOmD4HdQbX/2JSuLyS0WHzgagh5X2',
      description: 'Студент. Люблю пострелять',
      avatar: 'WomanWithGreenEyes.jpeg',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
